import {
  objectSchema as object,
  arraySchema as array,
  schemaRef as ref,
  definitions,
  textSchema as text,
  integerSchema as integer,
  hexSchema as hex,
  hashSchema as hash,
  addressSchema as address,
  decimalSchema as decimal,
  chainSchema as chain,
  dateSchema as date,
} from "./manifest-schema-parts.ts";

export const manifestSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "urn:morrow:campaign:v1",
  ...object({
    schemaVersion: { const: 1 },
    evidenceKind: { const: "live-read-verified" },
    campaignId: { enum: ["gate", "a", "b"] },
    generatedAt: date,
    implementationCommit: {
      anyOf: [{ type: "string", pattern: "^[0-9a-f]{40}$" }, { type: "null" }],
    },
    commitBlocker: { anyOf: [text, { type: "null" }] },
    networks: object({
      sourceEvmChainId: { const: "11155111" },
      destinationEvmChainId: { const: "102031" },
      attestcoinChainKey: { const: "1" },
    }),
    deployments: { ...array(ref("deployment"), 4), maxItems: 4 },
    tokens: {
      ...array(
        object({ address, chainId: chain, decimals: { const: 6 }, testToken: { const: true } }),
        2,
      ),
      maxItems: 2,
    },
    terms: object({
      protocolVersion: decimal,
      sourceEvmChainId: decimal,
      sourceVault: address,
      claimId: decimal,
      round: decimal,
      destinationEvmChainId: decimal,
      destinationMarket: address,
      seller: address,
      buyer: address,
      sourceToken: address,
      sourceFaceValueRaw: decimal,
      maturity: decimal,
      settlementToken: address,
      grossPurchasePriceRaw: decimal,
      feeBps: decimal,
      feeRecipient: address,
      fundBefore: decimal,
      assignBefore: decimal,
    }),
    identity: object({
      encodedTerms: { ...hex, minLength: 1154, maxLength: 1154 },
      termsHash: hash,
      saleId: hash,
      claimKey: hash,
    }),
    transactions: array(ref("transaction"), 3),
    proofs: array(ref("proof"), 1),
    snapshots: { ...array(ref("snapshot"), 2), maxItems: 2 },
    timeline: ref("artifact"),
    stateHistory: array(ref("artifact")),
    withdrawals: array(ref("transaction")),
    phaseTimings: array(
      object({
        action: text,
        observedAt: date,
        inclusionToObservedMs: { anyOf: [integer, { type: "null" }] },
        proofConstructionMs: { anyOf: [integer, { type: "null" }] },
      }),
    ),
    failures: array(object({ action: text, observedAt: date, error: text })),
    expectedOutcome: { enum: ["assigned-and-redeemed", "cancelled-refunded-and-redeemed"] },
    actualOutcome: object({
      sourceRoundState: { enum: [0, 1, 2, 3] },
      destinationState: { enum: [0, 1, 2, 3] },
      redeemed: { type: "boolean" },
    }),
    independentChecker: { anyOf: [ref("artifact"), { type: "null" }] },
    unresolvedFacts: array(text),
  }),
  definitions,
};
