[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
allow_paths = ["../packages/sdk/node_modules", "../node_modules/.pnpm"]
solc_version = "0.8.28"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "ipfs"
fs_permissions = [{ access = "read", path = "./test/fixtures" }]
remappings = ["@gluwa/asc-contracts/=../packages/sdk/node_modules/@gluwa/asc-contracts/", "@openzeppelin/contracts/=../packages/sdk/node_modules/@openzeppelin/contracts/"]

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 32
fail_on_revert = true

[profile.fork]
evm_version = "prague"
out = "out-fork"
cache_path = "cache-fork"
test = "fork"
